version: '3'
services:
  broker1:
    build: qpid-broker/.
    container_name: broker1
    ports:
     - "18080:80"
  broker2:
    build: qpid-broker/.
    container_name: broker2
    ports:
     - "28080:80"
  dispatcher1:
    build: qpid-dispatch/.
    container_name: dispatcher1
    environment:
      - QDROUTERD_CONFIG_FILE=/var/lib/qdrouterd/etc/qdrouterd-1.conf
    ports:
     - "5672:5672"
  dispatcher2:
    build: qpid-dispatch/.
    container_name: dispatcher2
    environment:
      - QDROUTERD_CONFIG_FILE=/var/lib/qdrouterd/etc/qdrouterd-2.conf
    ports:
     - "5673:5672"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
    ports:
     - "5775:5775/udp"
     - "6831:6831/udp"
     - "6832:6832/udp"
     - "5778:5778"
     - "16686:16686"
     - "14268:14268"
     - "9411:9411"
