FROM scholzj/qpid-dispatch:1.3.0
# FROM scholzj/qpid-dispatch:0.7.0

COPY --chown=qdrouterd:qdrouterd  qdrouterd-1.conf /var/lib/qdrouterd/etc/qdrouterd-1.conf
COPY --chown=qdrouterd:qdrouterd  qdrouterd-2.conf /var/lib/qdrouterd/etc/qdrouterd-2.conf
